---
title: "Tartan Students Fund Monthly Risk Comparison"
author: "Novdano"
date: "July 18, 2018"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#Parse  commandline argument
# args <- commandArgs(trailingOnly = T)
# print(class(args[[1]]))
# date <- args[[1]]
# date <- as.Date(date, "%Y-%m-%d")
# year <- as.numeric(format(date, "%Y"))
# month <- as.numeric(format(date, "%m"))
# if (month == 1){
#   month <- 12
#   year <- year - 1
# } else {
#   month <- month - 1
# }
# 
# month <- toString(month.abb[[month]])
# year <- toString(year)
# month_year <- paste(month,year, sep="")
```


```{r}
start_month <- 7
start_year <- 2017
end_month <- 6
end_year <- 2018
month_years <- c()
if (start_year != end_year){
  curr_month <- start_month
  curr_year <- start_year
  while (curr_month<=end_month || curr_year<end_year ){
    month_years <- c(month_years, paste(toString(month.abb[[curr_month]]), toString(curr_year), sep=""))
    if (curr_month == 12){
      curr_month <- 1
      curr_year <- curr_year + 1
    } else {
      curr_month <- curr_month+ 1
    }
  }
}
```

#VaR Summary (Daily)
```{r}
library(ggplot2)
library(stringr)
ninety_five_3Y <- rep(0,12)
ninety_nine_3Y <- rep(0,12)
ninety_five_1Y <- rep(0,12)
ninety_nine_1Y <- rep(0,12)
ninety_five_3M <- rep(0,12)
ninety_nine_3M <- rep(0,12)
for (i in 1:length(month_years)){
  month_year <- month_years[[i]]
  VaR.Data <- read.table(file=paste("VaR_Data/VaR_Numbers_", month_year, sep=""),sep='\t')[-1,]
  ninety_five_3Y[[i]] <- as.character.factor(VaR.Data[1,2])
  ninety_nine_3Y[[i]] <- as.character.factor(VaR.Data[2,2])
  ninety_five_1Y[[i]] <- as.character.factor(VaR.Data[3,2])
  ninety_nine_1Y[[i]] <- as.character.factor(VaR.Data[4,2])
  ninety_five_3M[[i]] <- as.character.factor(VaR.Data[5,2])
  ninety_nine_3M[[i]] <- as.character.factor(VaR.Data[6,2])
}
#95% VaR 3 Years
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_five_3Y)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) + 
  labs(title="95% VaR 3 Years") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
#99% VaR 3 Years
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_nine_3Y)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) +
  labs(title="99% VaR 3 Years") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
#95% VaR 1 Year
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_five_1Y)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) +
  labs(title="95% VaR 1 Year") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
#99% VaR 1 Year
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_nine_1Y)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) +
  labs(title="99% VaR 1 Year") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
#95% VaR 3 Months
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_five_3M)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) +
  labs(title="95% VaR 3 Months") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
#99% VaR 3 Months
df <- data.frame(month=factor(month_years, level=month_years), var=ninety_nine_3M)
ggplot(df,aes(x=df$month,y=df$var))+geom_bar(stat="identity", col="red", fill="red", alpha=0.2) +
  labs(title="99% VaR 3 Months") +
  labs(x="Months", y="VaR")+ theme(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(size=10, angle=45, hjus=1, vjust=1))
```

